services:
  - type: web
    name: movie-recommender-api
    env: python
    buildCommand: |
      cd c_engine && gcc -o recommender recommender.c -lm && gcc -o movie_system system_main.c auth.c comments.c chat.c mylist.c utils.c -lm && cd .. && pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
